logger:
  level: debug
  
rebalance_timer: 5m  # Interval to check nodes health

connect_timeout: 60s  # Timeout to dial node

request_timeout: 300s  # Timeout to check node health during rebalance

# The order in which resolvers are used to find an container id by name
resolve_order:
  - nns

server:
  - address: 0.0.0.0:8081

pprof:
  enabled: false # Enable pprof.
  address: localhost:8082
prometheus:
  enabled: true # Enable metrics.
  address: localhost:8083

# Wallet settings
wallet:
  path: /config/http-gw-wallet.json  # Path to wallet
  address: NMUTD9nsxSf3KM2pTHaqwjq67Lv7GdG3oG
  passphrase: one # Passphrase to decrypt wallet

peers:
  0:
    address: grpc://localhost:8080
    priority: 1
    weight: 1

rpc_endpoint: http://localhost:30333
