name: SlotMashine
supportedstandards: []
events:
  - name: "SlotResult"
    parameters:
      - name: "array"
        type: "Array"
  - name: "playerBalance"
    parameters:
      - name: "int"
        type: "Integer"
permissions:
    - methods: '*'
      events:
        - "SlotResult"
        - "playerBalance"
