name: SlotMashine
sourceurl: http://example.com/
safemethods: []
supportedstandards: []
events:
    - name: Hello world!
      parameters:
        - name: args
          type: Array
permissions:
    - methods: '*'
