name: SlotMashine
supportedstandards: []
events:
  - name: SlotResult
    parameters:
      - name: array
        type: Array
  - name: gameResult
    parameters:
      - name: int
        type: Integer
  - name: playerBalance
    parameters:
      - name: int
        type: Integer
permissions:
    - methods: '*'
      events:
        - SlotResult
        - gameResult
        - playerBalance
