name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    strategy:
      matrix:
        node-version: [ 17.x ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Starting NodeJs ${{ matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: build
        run: |
          yarn
          yarn build
        working-directory: frontend/casino
